export const FETCH_STUDENT_REQUEST = 'FETCH_STUDENT_REQUEST';
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
export const FETCH_STUDENT_ERROR = 'FETCH_STUDENT_ERROR';

export const SEARCH_STUDENT = 'SEARCH_STUDENT';

export const OPEN_STUDENT_POPUP = 'OPEN_STUDENT_POPUP';
export const CLOSE_STUDENT_POPUP = 'CLOSE_STUDENT_POPUP';